### ISSUE TITLE
replicaset: add the `roles` subcomand

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/tt#860]
We need to add analogs of:
* `tt cartridge replicasets add-roles`
* `tt cartridge replicasets remove-roles`

```[tasklist]
### Tasks
- [ ] https://github.com/tarantool/tt/issues/914
- [ ] https://github.com/tarantool/tt/issues/915
- [ ] https://github.com/tarantool/tt/issues/916
- [ ] https://github.com/tarantool/tt/issues/917
```
